-- =====================================================================
-- V1__create-table-courses.sql
-- Cria a tabela "courses".
-- =====================================================================

CREATE TABLE courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    slug VARCHAR(200) NOT NULL,
    description TEXT,
    level VARCHAR(20) NOT NULL DEFAULT 'BEGINNER',
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    instructor_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    version BIGINT,

    CONSTRAINT uk_courses_slug UNIQUE (slug),
    CONSTRAINT ck_courses_level CHECK (level  IN ('BEGINNER', 'INTERMEDIATE', 'ADVANCED')),
    CONSTRAINT ck_courses_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED'))
);

CREATE INDEX idx_courses_instructor_id ON courses (instructor_id);

CREATE INDEX idx_courses_status ON courses (status);