-- =====================================================================
-- V2__create-table-modules.sql
-- Cria a tabela "modules".
-- =====================================================================

CREATE TABLE modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    description TEXT,
    order_index INTEGER NOT NULL,
    course_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    version BIGINT,

    CONSTRAINT fk_modules_course
        FOREIGN KEY (course_id) REFERENCES courses (id)
);

CREATE INDEX idx_modules_course_id ON modules (course_id);