-- =====================================================================
-- V3__create-table-lessons.sql
-- Cria a tabela "lessons".
-- =====================================================================

CREATE TABLE lessons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    description TEXT,
    order_index INTEGER NOT NULL,
    video_url VARCHAR(500) NOT NULL,
    duration_seconds NUMERIC(21,0) NOT NULL,
    free_preview BOOLEAN NOT NULL,
    module_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    version BIGINT,

    CONSTRAINT fk_lessons_module
        FOREIGN KEY (module_id) REFERENCES modules (id)
);

CREATE INDEX idx_lessons_module_id ON lessons (module_id);